name: test1
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.2 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/test1/assets/images/iphone1313pro2.svg
    - packages/test1/assets/images/frame11.svg
    - packages/test1/assets/images/container.png
    - packages/test1/assets/images/vector.svg
    - packages/test1/assets/images/vectorstroke.svg
